# --- stress_q2 ---

from ._anvil_designer import stress_q2Template
from anvil import *
import anvil.server
import anvil.tables as tables
import anvil.tables.query as q
from anvil.tables import app_tables

from ... import assessment_logic

class stress_q2(stress_q2Template):
  def __init__(self, **properties):
    self.init_components(**properties)
    self.label_error.visible = False
    self.q2_next_btn.enabled = False  # Disable the Next button initially
    self.stress_q2_ans.text = str(assessment_logic.user_data['daily_exercise_mins'])

    # Initial check to see if the default value is valid
    self.live_validate() 

  def live_validate(self):
    """Validates input instantly (0-60, allows float) and toggles error/Next button."""
    input_str = self.stress_q2_ans.text

    # Validation: MIN 0, MAX 60
    valid, result = assessment_logic.validate_input(input_str, 0, 60)

    if valid:
      self.label_error.visible = False
      self.q2_next_btn.enabled = True # Enable the button
      return True

      # If we reach here, validation failed.
      # Use the error message generated by the validation utility
    self.label_error.text = result 
    self.label_error.visible = True
    self.q2_next_btn.enabled = False # Disable the button
    return False

  def handle_input_and_advance(self):
    # We rely on live_validate to check the final state before advancing
    if self.live_validate(): 
      # Data is valid, save it and advance
      # Re-running validation just to get the final numeric result
      _, result = assessment_logic.validate_input(self.stress_q2_ans.text, 0, 60)

      assessment_logic.user_data['daily_exercise_mins'] = result
      open_form("StressLevelPage.stress_q3")
      # No 'else' needed, as live_validate handles error display

  def q2_next_btn_click(self, **event_args):
    self.handle_input_and_advance()

  def stress_q2_ans_pressed_enter(self, **event_args):
    self.handle_input_and_advance()

    # --- THIS IS THE NEW CHANGE EVENT HANDLER ---
  def stress_q2_ans_change(self, **event_args):
    """This method is called when the text in this text box is edited"""
    self.live_validate()

  def q2_back_btn_click(self, **event_args):
    open_form("StressLevelPage.stress_q1")
    pass
