# --- stress_q6.py (FIXED for Strict Live Validation, 1-10 Integer) ---

from ._anvil_designer import stress_q6Template
from anvil import *
import anvil.server
import anvil.tables as tables
import anvil.tables.query as q
from anvil.tables import app_tables

from ... import assessment_logic

class stress_q6(stress_q6Template):
  def __init__(self, **properties):
    self.init_components(**properties)
    self.label_error.visible = False
    self.q6_submit_btn.enabled = False  # Disable the Submit button initially
    self.stress_q6_ans.text = str(assessment_logic.user_data['mood_level_1_10'])

    # Initial check to see if the default value is valid
    self.live_validate() 

  def live_validate(self):
    """Validates input instantly (1-10, MUST be integer) and toggles error/Submit button."""
    input_str = self.stress_q6_ans.text

    # Strict Validation: MIN 1, MAX 10
    valid, result = assessment_logic.validate_input(input_str, 1, 10)

    if valid:
      # Check 1: Must be a whole number (no decimals)
      if result != int(result):
        self.label_error.text = "Value must be a whole number (no decimals)."
        self.label_error.visible = True
        self.q6_submit_btn.enabled = False
        return False

        # If valid (1-10) and integer, validation is complete.
      self.label_error.visible = False
      self.q6_submit_btn.enabled = True # Enable the button
      return True

      # If we reach here, the input wasn't valid (not a number or out of 1-10 range).
      # We use the error message generated by the assessment_logic.validate_input
    self.label_error.text = result 
    self.label_error.visible = True
    self.q6_submit_btn.enabled = False 
    return False

  def handle_input_and_submit(self):
    # We rely on live_validate to check the final state before submitting
    if self.live_validate(): 
      # Data is valid, save it and submit
      # We already validated it's a whole number in 1-10, so we can cast to int safely.
      assessment_logic.user_data['mood_level_1_10'] = int(float(self.stress_q6_ans.text))

      # 2. PERFORM FINAL CALCULATION
      final_score = assessment_logic.calculate_total_stress()
      final_result = assessment_logic.get_result_feedback(final_score)

      # 3. OPEN RESULTS PAGE and pass the data (PASSING BOTH result AND score)
      # NOTE: This assumes your StressResultPage is fixed to accept 'result' and 'score'
      open_form("StressResultPage", result=final_result, score=final_score)
      # No 'else' needed, as live_validate handles error display

  def q6_submit_btn_click(self, **event_args):
    self.handle_input_and_submit()

  def stress_q6_ans_pressed_enter(self, **event_args):
    self.handle_input_and_submit()

    # --- NEW CHANGE EVENT HANDLER ---
  def stress_q6_ans_change(self, **event_args):
    """This method is called when the text in this text box is edited"""
    self.live_validate()