# --- stress_q4.py ---

from ._anvil_designer import stress_q4Template
from anvil import *
import anvil.server
import anvil.tables as tables
import anvil.tables.query as q
from anvil.tables import app_tables

from ... import assessment_logic

class stress_q4(stress_q4Template):
  def __init__(self, **properties):
    self.init_components(**properties)
    self.label_error.visible = False
    self.q4_next_btn.enabled = False  # Disable the Next button initially

    # Ensure initial value is handled gracefully (empty string if None)
    initial_value = assessment_logic.user_data['diet_quality_1_10']
    self.stress_q4_ans.text = str(initial_value) if initial_value is not None else ""

    # Initial check to see if the default value is valid
    self.live_validate() 

  def live_validate(self):
    """Validates input instantly (1-10, MUST be integer) and toggles error/Next button."""
    input_str = self.stress_q4_ans.text

    # 1. CRITICAL FIX: Pass require_integer=True to match the new function signature.
    # This tells the function to enforce whole numbers.
    valid, result = assessment_logic.validate_input(input_str, 1, 10, require_integer=True) 

    if valid:
      # If valid, the error message is cleared and the button is enabled.
      self.label_error.visible = False
      self.q4_next_btn.enabled = True 
      return True

      # 2. Corrected logic flow: If validation failed (not number, wrong range, or decimal), 
      # use the error message generated by validate_input.
    self.label_error.text = result # error message from validate_input
    self.label_error.visible = True
    self.q4_next_btn.enabled = False  
    return False

  def handle_input_and_advance(self):
    # We rely on live_validate to check the final state before advancing
    if self.live_validate(): 
      # Data is valid, save it and advance
      # Re-run validation just to safely retrieve the numeric result (float)
      _, result = assessment_logic.validate_input(self.stress_q4_ans.text, 1, 10, require_integer=True)

      # Since we enforced integer, we can safely cast the float result to an int
      assessment_logic.user_data['diet_quality_1_10'] = int(result)
      open_form("StressLevelPage.stress_q5")

  def q4_next_btn_click(self, **event_args):
    self.handle_input_and_advance()

  def stress_q4_ans_pressed_enter(self, **event_args):
    self.handle_input_and_advance()

  def stress_q4_ans_change(self, **event_args):
    """This method is called when the text in this text box is edited"""
    self.live_validate()

  def q4_back_btn_click(self, **event_args):
    open_form('StressLevelPage.stress_q3')
    pass